### ISSUE TITLE
Listen to two SQS Queues on the same Spring Boot app

### ISSUE THREAD

**Issue by durimkryeziu** [JaidenAshmore/java-dynamic-sqs-listener#116]
I cannot see anywhere in the docs or examples if this is possible:

- I have two different AWS accounts (may have more)
- Two different SQS Queues to listen to
- All that above on the same Spring Boot application

So is it possible to do that with this library? If so, can you give me some help here, please?

Thanks

**Comment by JaidenAshmore** [comment]
Hey,

I haven't actually tried with two different AWS accounts as applications that I have worked against have always had the SQS queues on a single AWS account, e.g. the doc I gave only describes how to do it with a single account: [How to: connect to AWS SQS Queue](https://github.com/JaidenAshmore/java-dynamic-sqs-listener/blob/2.x/doc/how-to-guides/how-to-connect-to-aws-sqs-queue.md).

As can be seen in the [QueueListenerConfiguration](https://github.com/JaidenAshmore/java-dynamic-sqs-listener/blob/2.x/java-dynamic-sqs-listener-spring/java-dynamic-sqs-listener-spring-core/src/main/java/com/jashmore/sqs/spring/config/QueueListenerConfiguration.java#L54) we  provide the default SqsAsyncClient that all of the SQS queues handle and so currently there is no support for two AWS accounts.

What I could do to support this is to provide a way for the consumer to provide a Map from an identifier to a specific Sqs Client. For example by default when you do:

```java
@QueueListener("myQueue")
```
it works as normal and will use a default `SqsAsyncClient`. Otherwise if you provide some sort of client identifier it can choose a specific client:

```java
@QueueListener(value = "myQueue", sqsClientIdentifier="accountOneIdentifier")
....
@QueueListener(value = "myOtherQueue", sqsClientIdentifier="accountTwoIdentifier")
```

You could then define the available clients in your application by doing something like:

```java
@Configuration
public class MyApplicationConfig {
    @Bean
    public SqsClientProvider sqsClientProvider() {
           final SqsAsyncClient firstClient = ...;
           final SqsAsyncClient secondClient = ....;

            return new SqsClientProvider(
                    ImmutableMap.of(
                           "accountOneIdentifier", firstClient,
                           "accountTwoIdentifier", secondClient,
            );
    }
}
```

So I think it should be possible to do and won't be a breaking change. I will start mucking around with it and get it into the 2.3.0 release. Hopefully I can have that released by this weekend 22/June.

Thanks for the interest!
Jaiden.

**Comment by JaidenAshmore** [comment]
Hmm actually spending a bit of time spiking this, it isn't as simple as I thought it would be.  As this will rely on a bit more structural changes to get this to work I will pin this to the 3.x release. I will be looking at this task next and will keep you posted.

**Comment by JaidenAshmore** [comment]
Hey,

Here is a workaround that you could utilise to help you keep going: https://github.com/JaidenAshmore/java-dynamic-sqs-listener/commit/c850ae77be2cbf1ec16581c05de60ee6fe708d36.

What it does it provides your own annotation where you can provide the identifier of the Sqs Client you want to use for this queue. It then looks at a map of clients and picks the one you need. 

### Caveats
- I have not tested this at all, I just wanted to get a theoretically workaround available to you.
- You cannot use the `VisibilityExtender` field in your message processing methods as that relies on the default `SqsAsyncClient`.
- The annotation was written using basic components of the core framework. E.g. it provides 10 message concurrency and each message downloaded and resolved is an individual call to SQS which is less efficient. You can take a look at [Core Implementations Overview](https://github.com/JaidenAshmore/java-dynamic-sqs-listener/blob/2.x/doc/core-implementations-overview.md) for an idea of implementations that you could use instead.

I will try and get a more robust solution in 3.0.0 and document it for future developers.

Thanks!

**Comment by durimkryeziu** [comment]
Thanks for reply @JaidenAshmore 

For now did a workaround with **Spring Cloud AWS Messaging** library, will wait till version 3.0 to see the option offered by this library

Thanks

**Comment by JaidenAshmore** [comment]
No worries at all.

I'm in my final stages of testing and documentation 
for this change. I'm looking at cutting a 3.0.0-M1 release this weekend.

**Comment by JaidenAshmore** [comment]
@durimkryeziu 

I have pushed up a branch for these changes. You can see the documentation for how to set this up at: https://github.com/JaidenAshmore/java-dynamic-sqs-listener/blob/issue/116_allow_multiple_aws_accounts/doc/how-to-guides/spring/spring-how-to-connect-to-multiple-aws-accounts.md

There is also an example that you can run at: https://github.com/JaidenAshmore/java-dynamic-sqs-listener/tree/issue/116_allow_multiple_aws_accounts/examples/multiple-aws-account-example

I will be looking at merging this into 3.x tomorrow and release a 3.0.0-M1 version that people can consume.

Happy for any feedback on whether this doesn't cover your use case or if you see any improvements.

Thanks!

**Comment by durimkryeziu** [comment]
@JaidenAshmore 
Thank you!
