### ISSUE TITLE
Listen to multiple AWS SQS in order.

### ISSUE THREAD

**Issue by RanjaniBR** [JaidenAshmore/java-dynamic-sqs-listener#137]
In my case, I need to listen to multiple queues and perform the same action after  receiving the message. But, I do not see documentation anywhere on how sqsLitener annotation polls queues in case of multiple queues. I want to poll first queue mentioned in the 'value' param first, if no message found then it should poll next queue. I mean listener should poll the queues in the given order. Is it possible to do this with sqsListener annotation ? I tried it. It is asynchronous polling on queues. Is it possible to achieve it by changing any configuration ?

**Comment by JaidenAshmore** [comment]
Hey,

No there is currently no way to do this with core listener annotations as like you said each listener was built with the idea that they can listen independently of each other and the current core `MessageListener`s do not allow the ability to listen on multiple queues.

I think the only way you could do this, without making significant changes to the core codebase to support this feature, would be to implement your own [MessageRetriever](https://github.com/JaidenAshmore/java-dynamic-sqs-listener/blob/3.x/java-dynamic-sqs-listener-api/src/main/java/com/jashmore/sqs/retriever/MessageRetriever.java) which would be able to transfer access to obtaining a message if their queue is empty. This would need to be done via some sort of static lock shared by each instance of that [MessageRetriever](https://github.com/JaidenAshmore/java-dynamic-sqs-listener/blob/3.x/java-dynamic-sqs-listener-api/src/main/java/com/jashmore/sqs/retriever/MessageRetriever.java) class.

To make this  [MessageRetriever](https://github.com/JaidenAshmore/java-dynamic-sqs-listener/blob/3.x/java-dynamic-sqs-listener-api/src/main/java/com/jashmore/sqs/retriever/MessageRetriever.java) usable via an annotation, you would then need to implement your own code to register a listener for this annotation, you can see a guide on how to do this at [Spring - How to add own queue listener](https://github.com/JaidenAshmore/java-dynamic-sqs-listener/blob/3.x/doc/how-to-guides/spring/spring-how-to-add-own-queue-listener.md). You can see an example of building for the `@QueueListener` annotation in the [BasicMessageListenerContainerFactory](https://github.com/JaidenAshmore/java-dynamic-sqs-listener/blob/3.x/java-dynamic-sqs-listener-spring/java-dynamic-sqs-listener-spring-core/src/main/java/com/jashmore/sqs/spring/container/basic/BasicMessageListenerContainerFactory.java).

I would probably so that the above would be a bit too much effort for what you want to achieve and unless there is a heavy demand for the edition of this feature I don't think I will be adding it into the core code of this library.

Let me know if any of that didn't make sense!
