### ISSUE TITLE
Please provide (system-)message attributes in a map rather than individually

### ISSUE THREAD

**Issue by kschroiff** [JaidenAshmore/java-dynamic-sqs-listener#139]
I'm currently PoCing your framework.

In prod, we make extensive use of message attributes - 8 or 9 of them.
Looking at your code, you seem to provide access via @MessageAttribute (MessageSystemAttribute) which is a bit cumbersome when dealing with many attributes really.

I sort of understand the reasoning behind your approach but getting access to the "raw" sqs data structures could make life easier for some at least.

**Comment by kschroiff** [comment]
Well, no worries. I forked the project and implemented the corresponding argument resolver.

**Comment by JaidenAshmore** [comment]
Hey sorry, my notifications weren't properly set up so I missed this. let me know if you have any more problems.

**Comment by kschroiff** [comment]
Hi Jaiden,
In a different scope - you mention that the concurrencyLevel is limited to 10. I understand that this is related to the 10 msg limit per (batch-)request in SQS. 

In our application, we require more than 10 parallel consumers/queue, thus as a workaround, we are spawning secondary threads per message in order to achieve a higher degree of concurrency.  However, this means that we have to acknowledge the receipt in the parent thread early (while the secondary thread is still busy). If the secondary thread crashes for whatever reason, the message is already deleted from the queue - which is not ideal.
It would be useful if there was something like "acknowledgeButDoNotDelete" in "Acknowledge" - thus letting the application care about the deletion.
Or is that already possible by now acknowledging at all? Haven't tried that ...

Of course, in a perfect world scenario, it would be great to have a concurrencyLevel > 10 in the library. Technically that should be possible by running parallel requests against SQS (which is, in fact, what we are doing in our current production system (but we'll have to replace this one soon)).

**Comment by JaidenAshmore** [comment]
Hey,

> In a different scope - you mention that the concurrencyLevel is limited to 10.

There is no limit to the concurrency level that you want to provide, you could have 1000 messages all being run concurrently if you wanted. You can see an example where I have changed the concurrency limit to 30 here: https://github.com/JaidenAshmore/java-dynamic-sqs-listener/blob/3.x/examples/sqs-listener-library-comparison/src/main/java/com/jashmore/sqs/examples/MessageListeners.java#L61.

This was one of the features that I wanted to provide as the Spring Cloud AWS Messaging did not provide for you out of the box because of that batch size limit.  You can find more information about changing the concurrency rate here: https://github.com/JaidenAshmore/java-dynamic-sqs-listener/blob/3.x/java-dynamic-sqs-listener-spring/java-dynamic-sqs-listener-spring-core/src/main/java/com/jashmore/sqs/spring/container/basic/QueueListener.java#L87.

What you may have seen is that there is a limit of 10 **extra** messages that can be prefetched using the [PrefetchingMessageRetriever](https://github.com/JaidenAshmore/java-dynamic-sqs-listener/blob/3.x/java-dynamic-sqs-listener-core/src/main/java/com/jashmore/sqs/retriever/prefetch/PrefetchingMessageRetriever.java) e.g. I desire 20 messages to be prefetched but I am happy to prefetch up to 30 if there are a lot more. In this case putting a max prefetch of 34 won't ever pull more than the 30 as it will pull a max of 10 more messages and see it is above 20 and stop requesting more.

Let me know if that didn't answer your question!

**Comment by kschroiff** [comment]
Ah, awesome. I misinterpreted this. Thx!
